# .github/workflows/build.yml

name: Build, Export and Publish Next.js App
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.19.x
      - run: |
          npm i
          npm run build
      - name: Next Pages
        uses: anorcle/next-pages@v1.0
      - name: Commit and push changes
        run: |
          git config --global user.name "a993897020"
          git config --global user.email "993897020@qq.com"
          git remote set-url origin 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@github.com/a993897020/record-life.git
          git add -A
          git commit -m "New Build"
          git push